### ISSUE TITLE
Unable to download the dataset conveniently

### ISSUE THREAD

**Issue by shenhai911** [csiro-robotics/Wild-Places#6]
Dear authors,
    Thank you for your excellent work. Now I want to download your dataset for my research, however, I had some trouble downloading the dataset, I have to download each file separately, as shown in the figure below
![example_for_downloading](https://github.com/csiro-robotics/Wild-Places/assets/26195360/a4dbdf4c-bf81-4045-bf71-943f41203694)

I wonder if you could provide a link to download the complete dataset.

Thank you very much again.

**Comment by shenhai911** [comment]
Hi, author, when I select zip archive method for downloading, I can not Click the button of "Request files", just as shown in the following figure:

![example_for_downloading2](https://github.com/csiro-robotics/Wild-Places/assets/26195360/be851c76-160e-4ef5-afbd-ac558c2692bb)

Looking forward to your help.

**Comment by JBKnights** [comment]
Hello,

In order to download the dataset more conveniently, we strongly reccomend you choose the "Download via WebDAV" option instead of downloading as a Zip archive.  This will send you a link via email containing instructions on how to download the files via a terminal command, as outlined in the README.pdf in the data portal description.

![image](https://github.com/csiro-robotics/Wild-Places/assets/47620360/2627f52e-3bd0-4e36-901a-03be30e32b31)
![image](https://github.com/csiro-robotics/Wild-Places/assets/47620360/353107d4-c8f2-4e92-9ff2-f8411a5d601d)

Let us know if you have any difficulty following these steps, and we can provide some further clarification.

**Comment by shenhai911** [comment]
> Hello,
> 
> In order to download the dataset more conveniently, we strongly reccomend you choose the "Download via WebDAV" option instead of downloading as a Zip archive. This will send you a link via email containing instructions on how to download the files via a terminal command, as outlined in the README.pdf in the data portal description.
> 
> ![image](https://user-images.githubusercontent.com/47620360/252822734-2627f52e-3bd0-4e36-901a-03be30e32b31.png) ![image](https://user-images.githubusercontent.com/47620360/252822808-353107d4-c8f2-4e92-9ff2-f8411a5d601d.png)
> 
> Let us know if you have any difficulty following these steps, and we can provide some further clarification.

Hello, thank you for your excellent work. Now, I can download the dataset conveniently with your help. Thanks again.
